# Generated by Django 5.2.6 on 2025-09-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('Movie_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Movie_name', models.CharField(max_length=100)),
                ('Release_date', models.DateField()),
                ('Director', models.CharField(max_length=50)),
                ('Actors', models.CharField(max_length=100)),
            ],
        ),
    ]
